version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
          environment:
            - MYSQL_DATABASE: "jdbc"
            - MYSQL_HOST: "127.0.0.1"
      - image: circleci/mysql:5.7
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: 'root'
    steps:
      - checkout

      - run:
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            mysql -h 127.0.0.1 -u root -proot < data.sql

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Build and test
          command: ./gradlew clean |
            rm -rf ~/.gradle/caches/* |
            ./gradlew test

      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
